### PR TITLE
feat: export live photo

### PR DESCRIPTION
**Pull request by lubbo**

### CODE REVIEW

**Comment by abentele** [comment]
Thanks @lubbo. Did some review and test and it seems to work. Integrated into master.
Sorry for the late reply, I've been under high work load...
Thank you for this contribution!

Btw.: I would prefer to name a "live photo" with a suffix like "-live-photo.mov", to distinguish such movies from other videos.

**Comment by abentele** [comment]
I've added a suffix "-live" to the generated file names.
This is to be able to distinguish them from "real" videos, and to be able to search for all live photos.

**Comment by lubbo** [comment]
The problem adding a suffix may be that some photo library manager (photoprism, immich,…) may be not able to auto link photo with respective live video… not sure about that…

**Comment by abentele** [comment]
thanks for discussing it - maybe a switch to enable the suffixes would be adequate?

**Pull request closed without merging**
